{
  description = "Homelab NixOS config";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixos-generators = {
      url = "github:nix-community/nixos-generators";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    impermanence.url = "github:nix-community/impermanence";
  };
  outputs = { self, nixpkgs, nixos-generators, agenix, disko, impermanence, ... }:
    let
      # Builds one real host's system. Parameterized by architecture so
      # future non-x86_64 hardware (a Raspberry Pi, an ARM thin client)
      # is just a different `system` value, not a rewrite — each host
      # still gets its own hardware-configuration.nix and disko.nix,
      # since disk layout and hardware never match between machines.
      mkHost = { hostname, system ? "x86_64-linux", extraModules ? [ ] }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          modules = [
            agenix.nixosModules.default
            disko.nixosModules.disko
            impermanence.nixosModules.impermanence
            ./modules/common.nix
            ./modules/secrets.nix
            ./hosts/${hostname}/disko.nix
          ] ++ extraModules;
        };
      dockerTestSystem = "x86_64-linux";
    in
    {
      nixosConfigurations = {
        # The REAL system for the NUC. No container-only overrides in
        # here — a bootloader and real networking are expected/required.
        archer = mkHost {
          hostname = "archer";
          extraModules = [
            ./modules/impermanence.nix
            # ./hosts/archer/hardware-configuration.nix
            #   ^ add this once the machine exists — generated by
            #   `nixos-generate-config` run on the target itself.
          ];
        };

        # Example shape for a future ARM node (e.g. a Raspberry Pi) —
        # uncomment and fill in once that hardware actually exists.
        # Likely needs its own hardware module rather than reusing
        # modules/impermanence.nix as-is: ZFS-on-ARM is less mature, and
        # the bootloader (systemd-boot assumes x86_64 UEFI) differs too.
        # rpi-node = mkHost {
        #   hostname = "rpi-node";
        #   system = "aarch64-linux";
        #   extraModules = [
        #     # ./hosts/rpi-node/hardware-configuration.nix
        #   ];
        # };
      };

      # Same common module, with container-only overrides layered on top,
      # built as a Docker image. This is what CI builds (and can boot +
      # smoke-test) on every branch, before anything touches real hardware.
      # Unaffected by the multi-host structure above — this stays x86_64
      # regardless of how many/which real hosts exist.
      packages.${dockerTestSystem}.homelab-docker-test = nixos-generators.nixosGenerate {
        system = dockerTestSystem;
        format = "docker";
        modules = [
          ./modules/common.nix
          ./modules/container-test.nix
        ];
      };
    };
}
