{
  description = "Homelab NixOS config";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixos-generators = {
      url = "github:nix-community/nixos-generators";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nixos-generators, agenix, ... }:
    let
      system = "x86_64-linux";
    in
    {
      # The REAL system. This is what actually runs on the machine once
      # hardware exists (or on an already-installed NixOS box today).
      # No container-only overrides in here — a bootloader and real
      # networking are expected and required.
      nixosConfigurations.homelab = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          agenix.nixosModules.default
          ./modules/common.nix
          ./modules/secrets.nix
          # ./hosts/homelab/hardware-configuration.nix
          #   ^ add this once the machine exists — generated by
          #   `nixos-generate-config` run on the target itself.
        ];
      };

      # Same common module, with container-only overrides layered on top,
      # built as a Docker image. This is what CI builds (and can boot +
      # smoke-test) on every branch, before anything touches real hardware.
      packages.${system}.homelab-docker-test = nixos-generators.nixosGenerate {
        inherit system;
        format = "docker";
        modules = [
          ./modules/common.nix
          ./modules/container-test.nix
        ];
      };
    };
}
